# Generated by Django 5.2.4 on 2025-08-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('genero', models.CharField(max_length=50)),
                ('duracion', models.PositiveIntegerField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.ImageField(upload_to='peliculas')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
