# Generated by Django 5.2.5 on 2025-08-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
