# Generated by Django 5.2.5 on 2025-08-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Peliculas', '0002_peliculas_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='fecha_lanzamiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
